load(".RData")
library (Seurat)
library (dplyr)
library (ggplot2)
library (magrittr)
library (gtools)
library (stringr)
library (Matrix)
library (tidyverse)
library (patchwork)
library(clustree)
library(plotly)
library(rtracklayer)
library(tidyHeatmap)
library(future)
library(DoubletFinder)
library(SoupX)
library(glmGamPoi)
ck_fcr <- FindVariableFeatures(ck_fcr, selection.method = "vst", nfeatures = 2000)
all.genes <- rownames(ck_fcr)
ck_fcr <- ScaleData(ck_fcr, features = all.genes)
save.image()
