suppressPackageStartupMessages(library(monocle))
args <- commandArgs(trailingOnly = TRUE)
base <- if (length(args) >= 1) args[[1]] else Sys.getenv("PSEUDOTIME_PROJECT_DIR", unset = ".")
cds <- readRDS(file.path(base, "selected_preview", "Epidermal_cells_I_monocle2_selected.rds"))
cat("PData columns:\n")
cat(paste(colnames(pData(cds)), collapse = "\n"), "\n")
cat("Cells:", ncol(cds), " genes:", nrow(cds), "\n")
cat("States:", paste(sort(unique(pData(cds)$State)), collapse = ","), "\n")
cat("Samples:", paste(unique(pData(cds)$Samples), collapse = ","), "\n")
scenic_summary <- if (length(args) >= 2) args[[2]] else file.path(base, "SCENIC_Summary.csv")
sc <- read.csv(scenic_summary, check.names = FALSE)
row <- sc[sc$TF_ID == "TraesCS4A02G001300", , drop = FALSE]
print(row[, c("Regulon", "TF_ID", "Best_Cluster", "Max_RSS", "Mean_AUC_Activity", "Target_Count")])
cat("Targets:\n", row$All_Targets, "\n")
